services:

  frps:
    image: snowdreamtech/frps:latest
    container_name: ff_frps
    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro
    ports:
      - "7000:7000"
    networks:
      - nginx_default
    restart: unless-stopped

  sync:
    build: ./sync
    container_name: ff_sync_hostinger
    environment:
      SRC_HOST: frps
      SRC_PORT: 15432
      SRC_DB:   ${SRC_DB}
      SRC_USER: ${SRC_USER}
      SRC_PASS: ${SRC_PASS}
      DST_HOST: postgres_db
      DST_PORT: 5432
      DST_DB:   post
      DST_USER: post
      DST_PASS: post25
    ports:
      - "3002:3002"
    networks:
      - nginx_default
    depends_on:
      - frps
    restart: unless-stopped

networks:
  nginx_default:
    external: true
